# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomSegment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BetterSegmentedControl', '1.0'

  # Pods for CustomSegment

  target 'CustomSegmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomSegmentUITests' do
    # Pods for testing
  end

end
